name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm install -g @zeit/ncc
    - run: ncc build src/index.js -o dist
    - uses: actions/upload-artifact@v1
      with:
        name: ncc-output
        path: dist/index.js